"use strict";
const asar = require("../node_modules/@electron/asar");
const path = require("path");
const ASAR = path.resolve(__dirname, "..", "..", "app.asar");
const files = asar.listPackage(ASAR);
const mm = files.find(f => f.includes("mammoth") && f.includes("zipfile"));
const fixed = mm.slice(1).split("\\").join("/");
console.log("path:", fixed);
const c = asar.extractFile(ASAR, fixed).toString();
const lines = c.split("\n").filter(l => l.includes("jszip") || l.includes("require"));
console.log("requires:", lines.join(" | "));
